server:
  port: 6000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sqldb-metlife-team06.mysql.database.azure.com:3306/maindb?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
#    username: team6
#    password: new1234!!
  datasource:
    url: jdbc:mysql://localhost:3306/metlife?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100

  logging:
    level:
      org:
        hibernate:
          SQL: INFO
