server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/data/dev
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/metlife?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      orm:
        jdbc:
          bind: trace
      properties:
        hibernate:
           format_sql: true
           dialect: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always

  logging:
    level:
      org:
        hibernate:
          SQL: debug
